name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        # working-directory: ./super-duper-inventory-app
        run: npm ci

      - name: Run ESLint
        # working-directory: ./super-duper-inventory-app
        run: npm run lint

      - name: Check Prettier formatting
        # working-directory: ./super-duper-inventory-app
        run: npm run format:check

      - name: Build project
        # working-directory: ./super-duper-inventory-app
        run: npm run build
